### ISSUE TITLE
process >= 1.6?

### ISSUE THREAD

**Issue by peti** [matterhorn-chat/aspell-pipe#1]
Is there any particular reason why this package depends on process 1.6.x or later? process is a GHC core package, and there is no version of GHC available today that actually has this version. The latest release, ghc 8.0.2, has process-1.4.3.0!

**Comment by jtdaugherty** [comment]
Process dependencies don't need to match GHC's bundled process library, and 1.6 is indeed on Hackage - but I depended on what I had installed. I can check on which old versions of process will work with the use of the API in this package, though.

Thanks!
