### ISSUE TITLE
Extra command-line flags

### ISSUE THREAD

**Issue by glguy** [matterhorn-chat/aspell-pipe#6]
What is your opinion on providing an escape hatch for providing arbitrary aspell command-line arguments? There are a lot of flags and I'd like to let users configure the underlying aspell themselves with extra languages and dictionaries in pass-through form in my configuration file.

**Comment by jtdaugherty** [comment]
Sounds good - how about 704d71b1919c76920370a47a6bf69ad28934da2c?

**Comment by jtdaugherty** [comment]
If that interface works for you, I'll merge it to `master` and make a release.

**Comment by glguy** [comment]
@jtdaugherty Thanks, that would work perfectly for me.

**Comment by jtdaugherty** [comment]
Okay, great. This is now released in `0.5`.
